---
- hosts: dev
  become: True
  tasks:
    
    - name: Start the container
      docker_container:
        name: SthithaPragna
        image: "sthithasunny/ansible:BUILD_ID"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
